server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_product
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  task:
    scheduling:
      pool:
        size=2:
audit-trails:
  url: http://localhost:8080/audit-trails/save
